# Generated by Django 5.2.10 on 2026-01-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_savedview'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedview',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
