# Generated by Django 5.2.10 on 2026-01-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_savedview_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedview',
            name='column_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
