# Generated by Django 5.2.10 on 2026-01-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_savedview_column_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedview',
            name='sorting',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
