# Generated by Django 5.2.10 on 2026-01-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedview',
            name='view_type',
            field=models.CharField(choices=[('client', 'Client'), ('task', 'Task'), ('workflow', 'Workflow')], default='client', max_length=20),
        ),
    ]
