# Generated by Django 5.2.10 on 2026-01-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_savedview_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='savedview',
            name='view_type',
            field=models.CharField(choices=[('client', 'Client'), ('task', 'Task')], default='client', max_length=20),
        ),
    ]
