# Generated by Django 5.2.10 on 2026-01-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_workflow_filters_alter_savedview_view_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletoken',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
