# Generated by Django 5.2.10 on 2026-01-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_googletoken_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='see_all_clients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='see_all_tasks',
            field=models.BooleanField(default=True),
        ),
    ]
